### ISSUE TITLE
Label of RadioGroup is too large

### ISSUE THREAD

**Issue by b-chiarini** [42BV/ui#387]
The label of a radio group is too large. Other inputs have a smaller label, so when put together, it doesn't look too well.

**Comment by gidomanders** [comment]
That's because the radio group uses a legend instead of a label tag. I don't think it's a good idea to change the layout in the library, because projects using this library might use custom styling for labels.

You could add className "radio-group" to the RadioGroup in your project and add these lines to your CSS:
```
.radio-group legend {
    font-size: 1rem;
}
```

**Comment by MrHus** [comment]
@gidomanders I think we should do this, bootstrap be damned!

If you look at the examples page: https://42bv.github.io/ui/storybook/?path=/story/form-example--jarb-form

The radio group is very jarringly due to the large label. 

I'm against overriding "legend" for all components. But we should fix this problem by either: fixing the legend for the `.radio-group` only, or by simply not using the `legend` in the RadioGroup.
