### ISSUE TITLE
DateRangePicker or DateTimeInput does not always send the date in the onChange

### ISSUE THREAD

**Issue by MrHus** [42BV/ui#479]
Note this is a bug we suspect to exists, and we do not know how to reproduce it yet.

~~DateRangePicker or DateTimeInput does not always seem to send the date in the onChange.
Sometimes the user enters a correct date / or selects it (we do not know) and the date will
not be send via the onChange.~~

Happens when changing the center of a valid date. For example when changing "2001-02-01" to "2001-01-01" manually by setting the cursor after the 02 and pressing backspace and then entering a 1.

**Comment by gidomanders** [comment]
I could reproduce it by adding constraints to the story:
```
setConstraints({
    User: {
        availability: {
            javaType: 'java.lang.String',
            types: ['text'],
            required: false,
            minimumLength: null,
            maximumLength: 50,
            fractionLength: null,
            radix: null,
            pattern: null,
            min: null,
            max: null,
            name: 'name'
        }
    }
});
```
In this screenshot you see what happens due to the validation error: the entire field becomes `null`:
 
<img width="1015" alt="Screenshot 2020-11-13 at 09 28 20" src="https://user-images.githubusercontent.com/1199214/99046606-49973a80-2593-11eb-89d7-f0391034d5e9.png">
