### ISSUE TITLE
ImageUpload allow for animated gifs

### ISSUE THREAD

**Issue by MrHus** [42BV/ui#481]
ImageUpload allow for animated gifs.

Think of something...

**Comment by gidomanders** [comment]
I don't think we will ever need animated gifs. If a user needs that, a regular file input should be used to upload animated gifs, so the cropping tool will not be used anyway. The libraries we use don't support animated gifs and cropping an animated image is probably hard. Since we don't have an actual use case for this since this issue was opened, I'm going to close this issue. Please feel free to reopen this issue when there is an actual use case so we can decide what we'll do then.
