### ISSUE TITLE
Usability issues with and improvements for typeahead component

### ISSUE THREAD

**Issue by JvW17** [42BV/ui#517]
Hi! As a UX designer at 42, I've found that your Typeahead components have some **usability issues that you might want to look into**. I'll inform you briefly why this is the case, and how to mitigate the issues. 

In short:

1. Users are aware of the text they just typed, so **only emphasise the predictive aspect** of the query suggestion (and not what the users has typed already, as is currently the case). This way, the search process becomes much more intuitive. [Google ](https://www.google.com/)is a prime example of this.
2. Don’t show more than 10 suggestions on desktop AND 4-8 suggestions on mobile. **Users ignore more than 10 suggestions** and **it slows down their search process**. This could be made into a pageSize-property, or you could a note on Storybook that the developer should account for this.
3. Avoid scrollbars. A typeahead component is interactive, so using a scrollbar in an interactive component is **a recipe for interaction disaster**. [Research studies conducted by the Baymard Institute](https://baymard.com/blog/autocomplete-design) shows that inline scroll areas often cause a wide range of interaction issues and should therefore generally be avoided. This too can be mitigated if the default result amount is set to a low(er) amount (like 4, 8 or 10).

This is how the current typeahead looks and works like, which please should be improved:
![typeahead_current](https://user-images.githubusercontent.com/61182196/104223947-989f0600-5444-11eb-8220-a39043ee9084.png)

This is how it should look and works like:
![research-media-file-7bd4b3cdd9af8e2576b56f1eb4ea9010](https://user-images.githubusercontent.com/61182196/104224729-ac973780-5445-11eb-9278-be2f069211fb.jpg)

[My used source](https://baymard.com/blog/autocomplete-design) is from Baymard Institute's website. This company conducts large-scale research studies on all aspects of the online user experience. Their various studies describe how usability issues arise and can be resolved.

Thanks for reading. Best regards,
Justin van Wijk

**Comment by gidomanders** [comment]
I changed the layout to invert the bold font, so my PR should fix your first point.

We already use pagination to limit the number of options to a maximum of 10. If you see more than 10 options, that's probably because your callback in the options property returns a bigger result. We pass the query, page and size to the callback, so you could utilize those or limit the result another way.

When limiting the size yourself, you could also do a check whether the screen is a mobile screen or not. I don't think it's a good idea to add a mobile screen check to this library.

The scrollbars are also related to the limitation of the number of options, so by doing what I opted above you can prevent scrollbars.

**Comment by gidomanders** [comment]
We have improved the Typeahead components by adding a maxResults property that allows you to limit the number of options displayed and add a "display additional results" button when the page size is large enough. You could also already limit the choices by specifying the page size. This should give you enough control over the number of options and play with different options for different screen sizes.

This means all points described are fixed, so I'm closing this issue.
