### ISSUE TITLE
JarbDateTimeInput validation keeps displaying `{property} is required` even when filled

### ISSUE THREAD

**Issue by TimQuist** [42BV/ui#636]
Not sure if to post this here or at `@42.nl/jarb-final-form` but decided to do it here.

When using the `JarbDateTimeInput` it marks the form as 'invalid' stating that the specified property `is required` even though the property is filled in.

This started occurring when using `"@42.nl/jarb-final-form": "2.1.3"`. 

In `"@42.nl/jarb-final-form": "2.1.2"` all seems to work fine.

See both codesandbox included:
[codesandbox 2.1.3 (bug)](https://codesandbox.io/s/42-jarb-final-form-validator-issue-2-1-3-nc3gwb?file=/src/App.tsx)
[codesandbox 2.1.2 (works fine)](https://codesandbox.io/s/42-jarb-final-form-validator-issue-2-1-2-jq3jrf)

To reproduce: Update the property using the calendar selector on the left, then attempt to save the form.

**Comment by gidomanders** [comment]
This is actually due to a [change in the required validator](https://github.com/42BV/jarb-final-form/commit/7264aff4bd7b5f87dde85d158d8c828156a209a8) in jarb-final-form, which was not tested well enough with a Date object as value.
I've [opened an issue](https://github.com/42BV/jarb-final-form/issues/41) there.
